categories: 分类
search: 搜索
tags: 标签
tagcloud: 标签云
tweets: 推文
prev: 上一页
next: 下一页
comment: 留言
archive_a: 归档
archive_b: 归档：%s
page: 第 %d 页
recent_posts: 最新文章
newer: 新哒!
older: 旧的..
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag
# categories: Categories
# search: Search
# tags: Tags
# tagcloud: Tag Cloud
# tweets: Tweets
# prev: Prev
# next: Next
# comment: Comments
# archive_a: Archives
# archive_b: "Archives: %s"
# page: Page %d
# recent_posts: Recent Posts
# newer: Newer
# older: Older
# share: Share
# powered_by: Powered by
# rss_feed: RSS Feed
# category: Category
# tag: Tag